//file:noinspection GroovyAssignabilityCheck
plugins {
    id 'blib-multiloader-fabric'
}

dependencies {
    implementation "com.just:just-codec:${project.just_codec_version}"
    include "com.just:just-codec:${project.just_codec_version}"
    implementation "com.just:just-core:${project.just_core_version}"
    include "com.just:just-core:${project.just_core_version}"
    implementation "com.just:just-goap:${project.just_goap_version}"
    include "com.just:just-goap:${project.just_goap_version}"

    modApi "com.terraformersmc:modmenu:${project.modmenu_version}"
    modApi "dev.architectury:architectury-fabric:${project.architectury_version}"
    modApi "me.shedaniel.cloth:cloth-config-fabric:${project.cloth_version}"

    // Compatibility
    blibModCompileOnly("com.avp.alien:avp_alien-fabric-1.21.1:${project.avp_alien_version}") {
        exclude group: 'com.blib'
    }
    blibModCompileOnly("com.avp.human:avp_human-fabric-1.21.1:${project.avp_human_version}") {
        exclude group: 'com.blib'
    }
}
