pluginManagement {
	includeBuild 'blib-gradle'

	repositories {
		mavenLocal()
		gradlePluginPortal()
		mavenCentral()
		maven { url = 'https://maven.fabricmc.net' }
		maven { url = 'https://maven.neoforged.net/releases' }
	}
}

plugins {
	id 'blib-multiloader-settings' version "${blib_gradle_version}"
}

rootProject.name = 'AVP-Predator'
include 'common'
include 'fabric'
include 'neoforge'
