plugins {
    id 'java-gradle-plugin'
    id 'maven-publish'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

repositories {
    gradlePluginPortal()
    mavenCentral()
    maven { url = 'https://maven.fabricmc.net' }
    maven { url = 'https://maven.neoforged.net/releases' }
}

dependencies {
    implementation 'com.diffplug.spotless:spotless-plugin-gradle:8.1.0'
    implementation 'net.fabricmc:fabric-loom:1.14-SNAPSHOT'
    implementation 'net.neoforged:moddev-gradle:2.0.137'
    implementation 'me.modmuss50:mod-publish-plugin:0.8.4'
    implementation 'org.gradle.toolchains:foojay-resolver:1.0.0'
}

gradlePlugin {
    plugins {
        blibMultiloaderSettings {
            id = 'blib-multiloader-settings'
            implementationClass = 'com.blib.gradle.BlibMultiloaderSettingsPlugin'
        }
        blibMultiloaderRoot {
            id = 'blib-multiloader-root'
            implementationClass = 'com.blib.gradle.BlibMultiloaderRootPlugin'
        }
        blibMultiloaderCommon {
            id = 'blib-multiloader-common'
            implementationClass = 'com.blib.gradle.BlibMultiloaderCommonPlugin'
        }
        blibMultiloaderLoader {
            id = 'blib-multiloader-loader'
            implementationClass = 'com.blib.gradle.BlibMultiloaderLoaderPlugin'
        }
        blibMultiloaderFabric {
            id = 'blib-multiloader-fabric'
            implementationClass = 'com.blib.gradle.BlibMultiloaderFabricPlugin'
        }
        blibMultiloaderNeoforge {
            id = 'blib-multiloader-neoforge'
            implementationClass = 'com.blib.gradle.BlibMultiloaderNeoForgePlugin'
        }
    }
}

publishing {
    repositories {
        maven {
            name = 'blib'
            url = uri('https://maven.bvanseghi.dev/blib/')

            credentials {
                username = System.getenv("AVP_MAVEN_USERNAME")
                password = System.getenv("AVP_MAVEN_PASSWORD")
            }

            authentication {
                basic(BasicAuthentication)
            }
        }
    }
}
