plugins {
    id 'blib-multiloader-common'
}

dependencies {
    compileOnly "com.just:just-codec:${project.just_codec_version}"
    compileOnly "com.just:just-core:${project.just_core_version}"
    compileOnly "com.just:just-goap:${project.just_goap_version}"

    // Compatibility
    compileOnly("com.avp.alien:avp_alien-common-1.21.1:${project.avp_alien_version}") {
        exclude group: 'com.blib'
    }
    compileOnly("com.avp.human:avp_human-common-1.21.1:${project.avp_human_version}") {
        exclude group: 'com.blib'
    }
}
