//file:noinspection GroovyAssignabilityCheck
plugins {
    id 'blib-multiloader-neoforge'
}

dependencies {
    implementation "com.just:just-codec:${project.just_codec_version}"
    implementation "com.just:just-core:${project.just_core_version}"
    implementation "com.just:just-goap:${project.just_goap_version}"

    blibMod "dev.architectury:architectury-neoforge:${project.architectury_version}"
    blibMod "me.shedaniel.cloth:cloth-config-neoforge:${project.cloth_version}"

    // Compatibility
    blibCompileOnly("com.avp.alien:avp_alien-neoforge-1.21.1:${project.avp_alien_version}") {
        exclude group: 'com.blib'
    }
    blibCompileOnly("com.avp.human:avp_human-neoforge-1.21.1:${project.avp_human_version}") {
        exclude group: 'com.blib'
    }
}
